name: app_test
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.7+12

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #shimmer animation
  shimmer: ^1.1.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  string_validator: ^0.3.0
  cupertino_icons: ^1.0.3
  firebase_auth: ^1.1.4
  cloud_firestore: ^2.1.0
  firebase_core: ^1.1.1
  firebase_storage: ^8.0.6
  firebase_messaging: ^10.0.0
  google_sign_in: ^5.0.3
  
  image_cropper: ^1.3.1
  image_picker: ^0.7.5
  cached_network_image: ^3.0.0
  emoji_picker_flutter: ^1.0.5
  flutter_svg: ^0.22.0 #Help us to use SVG in our app
  animations: ^2.0.0 #Help us to use animation easily also develop by flutter team
  provider: ^5.0.0 #Help keeping user status
  curved_navigation_bar: ^0.3.7 #navigation curved bottom bar
  uuid: ^3.0.4 #generate a unique ID for firestore storage
  flutter_typeahead: ^3.1.3 #auto complete the text Field
  focused_menu: ^1.0.2 #long hold on the tab to desplay stuf
  google_fonts: ^2.1.0
  dots_indicator: ^2.0.0
  flutter_email_sender: ^5.0.0 #send emails to admin report users
  multi_image_picker: ^4.7.12
  flutter_tags: ^0.4.8+2
  qr_flutter: ^4.0.0
  auto_size_text: ^2.1.0
  http: ^0.13.3
  flutter_spinkit: "^5.0.0"
  url_launcher: ^6.0.3
  flutter_launcher_icons: ^0.9.0
  linkwell: ^2.0.6 #url detect in text
  clipboard: ^0.1.2+8 #clipboard manager copy
  image_gallery_saver: ^1.6.7
  dio: ^4.0.0
  permission_handler: ^8.0.0+1
  fluttertoast: ^8.0.6
  jitsi_meet: ^3.0.0
  lottie: ^1.0.1
  share: ^2.0.1
  upgrader: ^3.3.0
  flutter_local_notifications: ^5.0.0+4
  expandable: ^5.0.1
  validators: ^3.0.0
  diff_match_patch: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/MeechuIcon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/courseimage/
    - assets/icon/
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
